version: '3.8'  # ou qualquer outra versão suportada pelo Docker Compose

services:
  phpyii2:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./app:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db:/var/lib/mysql  
    environment:
      MYSQL_ROOT_PASSWORD: testewii
      MYSQL_DATABASE: testewii2
      MYSQL_USER: usuarioteste
      MYSQL_PASSWORD: senhatest 
    ports:
      - 3306:3306